# Generated by Django 2.1.8 on 2020-10-25 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRomm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(db_column='제목', max_length=200)),
                ('game_status', models.BooleanField(db_column='진행 여부', default='Y')),
                ('game_date', models.DateTimeField(db_column='생성 시간', default=django.utils.timezone.now)),
            ],
        ),
    ]
