# Generated by Django 3.1.2 on 2020-10-25 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_gamenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTryNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_game_num', models.IntegerField(default=0)),
                ('try_game_result', models.CharField(db_column='try 결과', max_length=200)),
                ('try_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameTry', to='app.gamenum')),
                ('try_game_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
